name = "agencja-fun"
main = "src/worker.js"
compatibility_date = "2026-09-12"
account_id = "7060bcc794845705d4fb6b59f879384c"

[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
run_worker_first = ["/api/*"]

[env.dev]
name = "agencja-fun-dev"

[env.production]
name = "agencja-fun"
routes = [
  { pattern = "agencja.fun/*", zone_id = "6fec91fdd4edaf98891fab84bd60bb9d" },
  { pattern = "www.agencja.fun/*", zone_id = "6fec91fdd4edaf98891fab84bd60bb9d" }
]
